### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1482]
Seen on conode.dedis.ch:7771:

```
I : (     service.(*Service).SignatureRequest:  87) - Tue Sep 18 10:16:29 +0000 UTC 2018: Signed a message.

2 : (                      network.NewTLSConn: 369) - NewTLSConn to: tls://employees.org:6879
2 : (                      network.NewTLSConn: 369) - NewTLSConn to: tls://dedis.nella.org:6879
W : (          protocol.(*SubFtCosi).Dispatch: 333) - tls://conode.dedis.ch:7770 timed out while waiting for subleader commitment
W : (          protocol.(*SubFtCosi).Dispatch: 333) - tls://conode.dedis.ch:7770 timed out while waiting for subleader commitment
2 : (protocol.(*FtCosi).collectCommitments.func1:  40) - (subprotocol 1) subleader with id 3 failed, restarting subprotocol
2 : (protocol.(*FtCosi).collectCommitments.func1:  40) - (subprotocol 0) subleader with id 1 failed, restarting subprotocol
2 : (                      network.NewTLSConn: 369) - NewTLSConn to: tls://conode.gasser.blue:7770
panic: close of closed channel

goroutine 282 [running]:
github.com/dedis/cothority/ftcosi/protocol.(*SubFtCosi).HandleStop(0xc420336180, 0xc42058e410, 0xc420096820, 0xc4203f1868, 0x428029)
        /Users/ligasser/src/github.com/dedis/cothority/ftcosi/protocol/sub_protocol.go:460 +0x96
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Shutdown.func1()
        /Users/ligasser/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:97 +0x64
sync.(*Once).Do(0xc42019c3b8, 0xc4203f18c0)
        /usr/local/Cellar/go/1.10.1/libexec/src/sync/once.go:44 +0xbe
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Shutdown(0xc42019c340, 0x2, 0x2)
        /Users/ligasser/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:95 +0x4c
github.com/dedis/onet.(*TreeNodeInstance).closeDispatch(0xc42019a240, 0x2, 0x2)
        /Users/ligasser/src/github.com/dedis/onet/treenode.go:338 +0x225
github.com/dedis/onet.(*Overlay).nodeDelete(0xc4200bb4a0, 0xc4200242a0)
        /Users/ligasser/src/github.com/dedis/onet/overlay.go:533 +0x13f
github.com/dedis/onet.(*Overlay).nodeDone(0xc4200bb4a0, 0xc4200242a0)
        /Users/ligasser/src/github.com/dedis/onet/overlay.go:519 +0x4e
github.com/dedis/onet.(*TreeNodeInstance).Done(0xc42019a240)
        /Users/ligasser/src/github.com/dedis/onet/treenode.go:577 +0xdd
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Dispatch(0xc42019c340, 0xaa32c0, 0xc420541b60)
        /Users/ligasser/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:158 +0x18f3
github.com/dedis/onet.(*Overlay).CreateProtocol.func1(0xaa8d20, 0xc42019c340)
        /Users/ligasser/src/github.com/dedis/onet/overlay.go:572 +0x31
created by github.com/dedis/onet.(*Overlay).CreateProtocol
        /Users/ligasser/src/github.com/dedis/onet/overlay.go:571 +0x1d4
```

**Comment by jeffallen** [comment]
This problem went away when I upgraded the conode to the latest tip, 10d97441da186e01cd40990e06b833831b5c0300.

**Comment by jeffallen** [comment]
I saw this happening again, with tip. Reopening to remember to put in place at least a hacky fix.

**Comment by jeffallen** [comment]
Another instance:
```
panic: close of closed channel

goroutine 32197 [running]:
github.com/dedis/cothority/ftcosi/protocol.(*SubFtCosi).HandleStop(0xc4206be0c0, 0xc42058e910, 0xffffffffffffffff, 0xc4204bb7e0, 0x429e69)
        /home/cothority/go/src/github.com/dedis/cothority/ftcosi/protocol/sub_protocol.go:463 +0x96
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Shutdown.func1()
        /home/cothority/go/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:97 +0x64
sync.(*Once).Do(0xc420418628, 0xc4204bb838)
        /usr/local/go/src/sync/once.go:44 +0xbe
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Shutdown(0xc4204185b0, 0x2, 0x2)
        /home/cothority/go/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:95 +0x4c
github.com/dedis/onet.(*TreeNodeInstance).closeDispatch(0xc4200be5a0, 0x2, 0x2)
        /home/cothority/go/src/github.com/dedis/onet/treenode.go:344 +0x225
github.com/dedis/onet.(*Overlay).nodeDelete(0xc4200d5400, 0xc4200265a0)
        /home/cothority/go/src/github.com/dedis/onet/overlay.go:533 +0x13f
github.com/dedis/onet.(*Overlay).nodeDone(0xc4200d5400, 0xc4200265a0)
        /home/cothority/go/src/github.com/dedis/onet/overlay.go:519 +0x4e
github.com/dedis/onet.(*TreeNodeInstance).Done(0xc4200be5a0)
        /home/cothority/go/src/github.com/dedis/onet/treenode.go:583 +0xdd
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Dispatch(0xc4204185b0, 0xad4d20, 0xc420210eb0)
        /home/cothority/go/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:158 +0x18f3
github.com/dedis/onet.(*Overlay).CreateProtocol.func1(0xada860, 0xc4204185b0, 0xa6320c, 0x12, 0xe758f8b1ca7e985f, 0x243bc3f860c1a89a)
        /home/cothority/go/src/github.com/dedis/onet/overlay.go:572 +0x49
created by github.com/dedis/onet.(*Overlay).CreateProtocol
        /home/cothority/go/src/github.com/dedis/onet/overlay.go:571 +0x1fb
```

**Comment by jeffallen** [comment]
This is no longer happening, close again.
