### ISSUE TITLE
FTCoSi panic

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#1582]
When running 1000 transactions in parallel, I got an error in ftcosi at the following line:

https://github.com/dedis/cothority/blob/master/ftcosi/protocol/sub_protocol.go#L461

The stack-trace is the following:

```
2 18/15/11 10:48:28.155362200: (   byzcoin.(*Service).startPolling.func1: 1281) - tls://192.168.0.42:7774 Starting new block 19
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7b73d0]

goroutine 6053 [running]:
github.com/dedis/onet.(*TreeNodeInstance).Root(0xc420236000, 0x4cba2e)
	/Users/ligasser/src/github.com/dedis/onet/treenode.go:133 +0x30
github.com/dedis/cothority/ftcosi/protocol.(*SubFtCosi).HandleStop(0xc420198b60, 0xc4202d59f0, 0xc420078680, 0xc4202d97e0, 0x428029)
	/Users/ligasser/src/github.com/dedis/cothority/ftcosi/protocol/sub_protocol.go:461 +0x43
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Shutdown.func1()
	/Users/ligasser/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:97 +0x64
sync.(*Once).Do(0xc4204c23b8, 0xc4202d9838)
	/usr/local/Cellar/go/1.10.1/libexec/src/sync/once.go:44 +0xbe
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Shutdown(0xc4204c2340, 0x2, 0x2)
	/Users/ligasser/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:95 +0x4c
github.com/dedis/onet.(*TreeNodeInstance).closeDispatch(0xc4201b4480, 0x2, 0x2)
	/Users/ligasser/src/github.com/dedis/onet/treenode.go:344 +0x225
github.com/dedis/onet.(*Overlay).nodeDelete(0xc420180000, 0xc42026d740)
	/Users/ligasser/src/github.com/dedis/onet/overlay.go:506 +0x13f
github.com/dedis/onet.(*Overlay).nodeDone(0xc420180000, 0xc42026d740)
	/Users/ligasser/src/github.com/dedis/onet/overlay.go:492 +0x4e
github.com/dedis/onet.(*TreeNodeInstance).Done(0xc4201b4480)
	/Users/ligasser/src/github.com/dedis/onet/treenode.go:583 +0xdd
github.com/dedis/cothority/ftcosi/protocol.(*FtCosi).Dispatch(0xc4204c2340, 0xb1c9e0, 0xc4208282d0)
	/Users/ligasser/src/github.com/dedis/cothority/ftcosi/protocol/protocol.go:158 +0x18f3
github.com/dedis/onet.(*Overlay).CreateProtocol.func1(0xb22a00, 0xc4204c2340, 0xc420148760, 0x19, 0x8e5db02624d993b9, 0xa12dfd9efb78b7b7)
	/Users/ligasser/src/github.com/dedis/onet/overlay.go:545 +0x49
created by github.com/dedis/onet.(*Overlay).CreateProtocol
	/Users/ligasser/src/github.com/dedis/onet/overlay.go:544 +0x1f8
```

**Comment by jeffallen** [comment]
The crash came from the call to p.Root here:
```go
func (p *SubFtCosi) HandleStop(stop StructStop) error {
	if !isValidSender(stop.TreeNode, p.Root()) {
```

Root calls treeNodeInstance's Tree() and dereferences the result without checking for nil (treenode.go:132). Tree() could return nil if a cache entry expires. It is looking for field Root in this type:

```go
type Tree struct {
	ID     TreeID
	Roster *Roster
	Root   *TreeNode
}
```

The deref was for addr 0x18. sizeof(Id) == 16, sizeof(*Roster) == 8 on 64 bit machines, and thus the offset of Root would be 0x18.

Smoking gun, fix coming.
