### ISSUE TITLE
block interval 200ms - spurious view changes

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1613]
Seen on securekg conodes, I tried to make a block interval of 200ms, and it seemed to work, but then died with:

```
2 : (    byzcoin.(*Service).sendViewChangeReq: 120) - tls://localhost:18004 sending view-change request for view: ID: e5067520fb4f0ae9a8dc834adeb629f70d2f9b990316a541ddae611838394670, Gen: d41a65bd68911e848e9c40ad7053a66b01946e66e96218a8ebb3b7ccf4b81ae1, Leader: 1
panic: heartbeat monitors are started after the creation of the genesis block, so the block should always exist

goroutine 35 [running]:
github.com/dedis/cothority/byzcoin.(*Service).monitorLeaderFailure.func1(0xc4200d4c60)
	/go/src/github.com/dedis/cothority/byzcoin/service.go:1844 +0x43a
created by github.com/dedis/cothority/byzcoin.(*Service).monitorLeaderFailure
	/go/src/github.com/dedis/cothority/byzcoin/service.go:1836 +0xc5
W : ( viewchange.(*Controller).processAnomaly: 253) - Controller is not accepting anomalies for earlier views
```

**Comment by Gilthoniel** [comment]
My guess of what is happening here is that the skipchain is known but the error message is misleading because an error can be returned when the latest block request to the DB fails. This could easily happen if a conode misses a block propagation but get a forward link to it (height > 0) because we store the forward link anyway. Is that what we want btw ?! Related to #1793
