### ISSUE TITLE
Collective Signing error, panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by omidraha** [dedis/cothority#1689]
In accordance with the instructions, but :
https://github.com/dedis/cothority#collective-signing

```go
or@omid:~/ws$ go get github.com/dedis/cothority/ftcosi
or@omid:~/ws$ export DEDIS_GROUP=$(go env GOPATH)/src/github.com/dedis/cothority/dedis-cothority.toml
or@omid:~/ws$ date > /tmp/my_file
or@omid:~/ws$ ~/go/bin/ftcosi  sign --group $DEDIS_GROUP /tmp/my_file | tee sig.json
```
Traceback:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/dedis/kyber/sign/cosi.Verify(0x974920, 0xc420098340, 0xc4200b4d00, 0x4, 0x4, 0xc4200aec60, 0x20, 0x20, 0xc420156623, 0x0, ...)
	/home/or/go/src/github.com/dedis/kyber/sign/cosi/cosi.go:173 +0x9f7
main.signStatement(0x96e600, 0xc4200b0080, 0xc4200b4cc0, 0x0, 0x0, 0x0)
	/home/or/go/src/github.com/dedis/cothority/ftcosi/client.go:154 +0x614
main.sign(0x96e600, 0xc4200b0080, 0x7fff1bdd2f4c, 0x3f, 0x1, 0x4, 0x912001)
	/home/or/go/src/github.com/dedis/cothority/ftcosi/client.go:116 +0x22a
main.signFile(0xc4200f2840, 0x0, 0xc4200f2840)
	/home/or/go/src/github.com/dedis/cothority/ftcosi/client.go:47 +0x16a
gopkg.in/urfave/cli%2ev1.HandleAction(0x862c40, 0x931fd0, 0xc4200f2840, 0xc4200c6500, 0x0)
	/home/or/go/src/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.Command.Run(0x910db9, 0x4, 0x0, 0x0, 0xc420099140, 0x1, 0x1, 0x92cceb, 0x58, 0x0, ...)
	/home/or/go/src/gopkg.in/urfave/cli.v1/command.go:210 +0xa36
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200c8b60, 0xc4200b20f0, 0x5, 0x5, 0x0, 0x0)
	/home/or/go/src/gopkg.in/urfave/cli.v1/app.go:255 +0x6a0
main.main()
	/home/or/go/src/github.com/dedis/cothority/ftcosi/ftcosi.go:140 +0xc53
```
Info:
```
or@omid:~/ws$ go version
go version go1.10.4 linux/amd64
```

**Comment by omidraha** [comment]
I think the problem is related to cothority public servers:

```
 $ cat $DEDIS_GROUP  

[[servers]]
  Address = "tls://conode.dedis.ch:7770"
  Public = "036bf316e1ea6e7e99e0bb713419d16c0b6794bf9dc442cc4cf36c3f935e93cf"
  Description = "EPFL Cothority-server"

[[servers]]
  Address = "tls://dedis.nella.org:6879"
  Public = "4e3008c1a2b6e022fb60b76b834f174911653e9c9b4156cc8845bfb334075655"
  Description = "Jeff's server - dedis.nella.org"

[[servers]]
  Address = "tls://conode.gasser.blue:7770"
  Public = "e5e23e58539a09d3211d8fa0fb3475d48655e0c06d83e93c8e6e7d16aa87c106"
  Description = "Ineiti's Cothority-server"

[[servers]]
  Address = "tls://employees.org:6879"
  Suite = "Ed25519"
  Public = "1e7f67a33f945f13db2f51ae1547e5678d88e40cd599611a4f7deede29d8abea"
  Description = "jra@employees.org"
```
Because I don't have this problem, when I use my own node.
