### ISSUE TITLE
Couldn't save file: struct has no serializable fields (field nonces) (field Auth)

### ISSUE THREAD

**Issue by omidraha** [dedis/cothority#1693]
Hi,
I [have](https://omidraha.com/en/latest/src/cothority/tips.html#install) three conodes, 

when I want to connect to a node. as [docs](https://github.com/dedis/cothority/blob/master/cisc/CLI.md#connecting-to-one-conode): 

```
$ cisc link pin 192.168.0.180:6879 314866
Successfully linked with tcp://192.168.0.180:6879
```
The output of command print `Successfully` but there is an error on conode server (here 192.168.0.180)
Traceback:

```
E : (network.Marshal: 128) - Error for protobuf encoding: struct has no serializable fields (field nonces) (field Auth) &{Identities:map[��䫛�x@f���)��U�S���WX̽*�:0xc420367a60] OldSkipchainKey:<nil> SkipchainKeyPair:<nil> Auth:0xc42006a960}
E : (network.Marshal: 130) - goroutine 780 [running]:
runtime/debug.Stack(0xc42036f070, 0xc42036f088, 0x5d17a0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/dedis/onet/log.Stack(0x3, 0x23)
	/go/src/github.com/dedis/onet/log/testutil.go:80 +0x22
github.com/dedis/onet/network.Marshal(0x8b19c0, 0xc42017cc30, 0xc42005b1d8, 0x5d1272, 0x3, 0x3, 0xc42005b258)
	/go/src/github.com/dedis/onet/network/encoding.go:130 +0x331
github.com/dedis/onet.(*Context).Save(0xc42001f740, 0xc714c8, 0x7, 0x7, 0x8b19c0, 0xc42017cc30, 0xc42001ee80, 0x2)
	/go/src/github.com/dedis/onet/context.go:128 +0x42
github.com/dedis/cothority/identity.(*Service).save(0xc42006a900)
	/go/src/github.com/dedis/cothority/identity/service.go:750 +0xb2
github.com/dedis/cothority/identity.(*Service).PinRequest(0xc42006a900, 0xc4201d40a0, 0xdcbf49ff825883, 0xff76cc8800e2b5ed, 0x7cedeeff94bc90, 0x0)
	/go/src/github.com/dedis/cothority/identity/service.go:129 +0x1d5
github.com/dedis/cothority/identity.(*Service).PinRequest-fm(0xc4201d40a0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/dedis/cothority/identity/service.go:831 +0x34
reflect.Value.call(0x8e8be0, 0xc42019c630, 0x13, 0x9a528a, 0x4, 0xc42005b860, 0x1, 0x1, 0x922ae0, 0xc4201d4040, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x8e8be0, 0xc42019c630, 0x13, 0xc42005b860, 0x1, 0x1, 0x0, 0x0, 0xc420027100)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/dedis/onet.(*ServiceProcessor).ProcessClientRequest.func1(0x8fb101, 0xc4204d81ee, 0xa, 0x8e8be0, 0xc42019c630, 0xa15320, 0x922ae0, 0xc42005b930, 0xc42019c3c0, 0x2, ...)
	/go/src/github.com/dedis/onet/processor.go:137 +0x326
github.com/dedis/onet.(*ServiceProcessor).ProcessClientRequest(0xc42019c3c0, 0xc42011a100, 0xc4204d81ee, 0xa, 0xc4204d6000, 0x2a, 0x600, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/dedis/onet/processor.go:144 +0xc7
github.com/dedis/onet.wsHandler.ServeHTTP(0x9a64c9, 0x8, 0xa0fa20, 0xc42006a900, 0xa0ff60, 0xc420388000, 0xc42011a100)
	/go/src/github.com/dedis/onet/websocket.go:179 +0x527
net/http.(*ServeMux).ServeHTTP(0xc42007fe30, 0xa0ff60, 0xc420388000, 0xc42011a100)
	/usr/local/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4200876c0, 0xa0ff60, 0xc420388000, 0xc42011a100)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420bff0e0, 0xa106e0, 0xc4204b20c0)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b

E : (identity.(*Service).save: 752) - Couldn't save file: struct has no serializable fields (field nonces) (field Auth)
2 : (onet.wsHandler.ServeHTTP: 178) - ws request from 192.168.0.107:37980: Identity/PinRequest
3 : (identity.(*Service).PinRequest: 117) - PinRequest tls://192.168.0.180:6879
3 : (identity.(*Service).save: 749) - Saving service
1 : (identity.(*Service).PinRequest: 130) - Successfully registered PIN/Public 314866 4777ec260445e6692dee20a5295c7d9863e1f49a3d53993ccfb38da1dedbc9e9
```

Then when I want to create an identify as [docs](https://github.com/dedis/cothority/blob/master/cisc/CLI.md#creating-an-identity):

```
$ cisc skipchain create group.toml 
Found full link to conode: 192.168.0.180:6879 4777ec260445e6692dee20a5295c7d9863e1f49a3d53993ccfb38da1dedbc9e9
Creating new blockchain-identity for omid in roster [tls://192.168.0.180:6879 tls://192.168.0.181:6879 tls://192.168.0.182:6879]
New cisc-id is: 1d1ef434893ec192ac95ae117f46c17d8fc1af093cda0122117356d8f12b5a06
```
The output of command seems successful, but there is an error on conode servers:

Traceback of `192.168.0.180` conode servers:

```
2 : (onet.wsHandler.ServeHTTP: 178) - ws request from 192.168.0.107:37982: Identity/Authenticate
2 : (onet.wsHandler.ServeHTTP: 178) - ws request from 192.168.0.107:37984: Identity/CreateIdentity
3 : (identity.(*Service).CreateIdentityInternal: 286) - tls://192.168.0.180:6879 Creating new identity with data Threshold: 2
Owner: omid

3 : (identity.(*Service).CreateIdentityInternal: 290) - Creating Data-skipchain Threshold: 2
Owner: omid

2 : (skipchain.(*Service).StoreSkipBlock: 177) - Creating new skipchain with roster [tls://192.168.0.180:6879 tls://192.168.0.181:6879 tls://192.168.0.182:6879]
3 : (skipchain.(*Service).StoreSkipBlock: 349) - Propagate 1 blocks
3 : (skipchain.(*Service).startPropagation: 1145) - Starting to propagate for service tls://192.168.0.180:6879
3 : (      messaging.NewPropagationFunc.func2: 114) - tls://192.168.0.181:6879 Starting to propagate *skipchain.PropagateSkipBlocks
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 455) - Starting node tls://192.168.0.180:6879 (20a9432b-d8eb-5c69-a544-1652fe48f960): SkipchainPropagate
3 : (network.(*Router).connect: 204) - tls://[::]:6879 Connecting to tls://192.168.0.180:6879
2 : (network.NewTLSConn: 369) - NewTLSConn to: tls://192.168.0.180:6879
2 : (network.NewTLSListenerWithListenAddr.func1: 243) - Got new connection request from: 172.17.0.1:37448
3 : (network.makeVerifier.func1.1: 276) - verify cert -> b097aca656644fc86eaade5f3e14d74a922e7d5e4d0e2f1a05d7a2750edfde02
3 : (network.makeVerifier.func1.1: 276) - verify cert -> b097aca656644fc86eaade5f3e14d74a922e7d5e4d0e2f1a05d7a2750edfde02
3 : (network.(*Router).connect: 210) - tls://[::]:6879 Connected to tls://192.168.0.180:6879
3 : (network.(*Router).handleConn: 273) - tls://[::]:6879 Handling new connection from tls://192.168.0.180:6879
3 : (network.(*Router).handleConn: 273) - tls://[::]:6879 Handling new connection from tls://192.168.0.180:6879
3 : (messaging.(*Propagate).Dispatch: 165) - tls://192.168.0.180:6879 Got data from tls://192.168.0.180:6879 and setting timeout to 15s
3 : (         messaging.(*Propagate).Dispatch: 182) - tls://192.168.0.180:6879 Sending to children
3 : (               network.(*Router).connect: 204) - tls://[::]:6879 Connecting to tls://192.168.0.181:6879
2 : (                      network.NewTLSConn: 369) - NewTLSConn to: tls://192.168.0.181:6879
3 : (               network.(*Router).connect: 204) - tls://[::]:6879 Connecting to tls://192.168.0.182:6879
2 : (                      network.NewTLSConn: 369) - NewTLSConn to: tls://192.168.0.182:6879
3 : (            network.makeVerifier.func1.1: 276) - verify cert -> 7a6e03ba71bd87aa1a62972eb20788ab21250ea23ad3166e995225278b227983
3 : (            network.makeVerifier.func1.1: 276) - verify cert -> 2c84becca826a737560d572ce1f4e4bbda47f32044611e660dcf5b27cf2c30c2
3 : (               network.(*Router).connect: 210) - tls://[::]:6879 Connected to tls://192.168.0.181:6879
3 : (            network.(*Router).handleConn: 273) - tls://[::]:6879 Handling new connection from tls://192.168.0.181:6879
3 : (               network.(*Router).connect: 210) - tls://[::]:6879 Connected to tls://192.168.0.182:6879
3 : (            network.(*Router).handleConn: 273) - tls://[::]:6879 Handling new connection from tls://192.168.0.182:6879
3 : (         messaging.(*Propagate).Dispatch: 215) - tls://192.168.0.180:6879 done, isroot: true
3 : (           onet.(*TreeNodeInstance).Done: 571) - tls://192.168.0.180:6879 (20a9432b-d8eb-5c69-a544-1652fe48f960): SkipchainPropagate has finished. Deleting its resources
3 : (  onet.(*TreeNodeInstance).closeDispatch: 328) - Closing node tls://192.168.0.180:6879 (20a9432b-d8eb-5c69-a544-1652fe48f960): SkipchainPropagate
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 459) - Closing reader
3 : (         messaging.propagateStartAndWait: 142) - Finished propagation with 3 replies
3 : (     skipchain.(*Service).StoreSkipBlock: 359) - Block added, replying. New latest is: 1d1ef434893ec192ac95ae117f46c17d8fc1af093cda0122117356d8f12b5a06, at index 0
3 : (      messaging.NewPropagationFunc.func2: 114) - tls://192.168.0.180:6879 Starting to propagate *identity.PropagateIdentity
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 455) - Starting node tls://192.168.0.180:6879 (12ac5a8f-fd1c-5145-b24b-0f3c30ebe988): IdentityPropagateID
3 : (         messaging.(*Propagate).Dispatch: 165) - tls://192.168.0.180:6879 Got data from tls://192.168.0.180:6879 and setting timeout to 10s
3 : (identity.(*Service).propagateIdentityHandler: 704) - Storing identity in tls://192.168.0.180:6879
3 : (  identity.(*Service).setIdentityStorage: 725) - tls://192.168.0.180:6879 1d1ef434893ec192 map[omid:0xc420219de0]
3 : (                identity.(*Service).save: 749) - Saving service
E : (                         network.Marshal: 128) - Error for protobuf encoding: struct has no serializable fields (field nonces) (field Auth) &{Identities:map[��䫛�x@f���)��U�S���WX̽*�:0xc420367a60 �4�>�����F�}���	<�"sV��+Z:0xc42027ef20] OldSkipchainKey:<nil> SkipchainKeyPair:<nil> Auth:0xc42006a960}
E : (                         network.Marshal: 130) - goroutine 806 [running]:
runtime/debug.Stack(0xc4201257c8, 0xc4201257e0, 0x5d17a0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/dedis/onet/log.Stack(0x3, 0x23)
	/go/src/github.com/dedis/onet/log/testutil.go:80 +0x22
github.com/dedis/onet/network.Marshal(0x8b19c0, 0xc42017cc30, 0xc420239930, 0x5d1272, 0x3, 0x3, 0xc4202399b0)
	/go/src/github.com/dedis/onet/network/encoding.go:130 +0x331
github.com/dedis/onet.(*Context).Save(0xc42001f740, 0xc714c8, 0x7, 0x7, 0x8b19c0, 0xc42017cc30, 0x610000c4202399e0, 0x5d15ac)
	/go/src/github.com/dedis/onet/context.go:128 +0x42
github.com/dedis/cothority/identity.(*Service).save(0xc42006a900)
	/go/src/github.com/dedis/cothority/identity/service.go:750 +0xb2
github.com/dedis/cothority/identity.(*Service).setIdentityStorage(0xc42006a900, 0xc42011b174, 0x20, 0x20, 0xc42027ef20)
	/go/src/github.com/dedis/cothority/identity/service.go:727 +0x209
github.com/dedis/cothority/identity.(*Service).propagateIdentityHandler(0xc42006a900, 0x901220, 0xc4201cd4d0)
	/go/src/github.com/dedis/cothority/identity/service.go:705 +0x2d1
github.com/dedis/cothority/identity.(*Service).(github.com/dedis/cothority/identity.propagateIdentityHandler)-fm(0x901220, 0xc4201cd4d0)
	/go/src/github.com/dedis/cothority/identity/service.go:812 +0x3e
github.com/dedis/cothority/messaging.(*Propagate).Dispatch(0xc420224050, 0x0, 0x0)
	/go/src/github.com/dedis/cothority/messaging/propagate.go:170 +0xd79
github.com/dedis/onet.(*Overlay).CreateProtocol.func1(0xa11060, 0xc420224050)
	/go/src/github.com/dedis/onet/overlay.go:572 +0x31
created by github.com/dedis/onet.(*Overlay).CreateProtocol
	/go/src/github.com/dedis/onet/overlay.go:571 +0x1d4

E : (                identity.(*Service).save: 752) - Couldn't save file: struct has no serializable fields (field nonces) (field Auth)
3 : (         messaging.(*Propagate).Dispatch: 182) - tls://192.168.0.180:6879 Sending to children
3 : (         messaging.(*Propagate).Dispatch: 215) - tls://192.168.0.180:6879 done, isroot: true
3 : (           onet.(*TreeNodeInstance).Done: 571) - tls://192.168.0.180:6879 (12ac5a8f-fd1c-5145-b24b-0f3c30ebe988): IdentityPropagateID has finished. Deleting its resources
3 : (  onet.(*TreeNodeInstance).closeDispatch: 328) - Closing node tls://192.168.0.180:6879 (12ac5a8f-fd1c-5145-b24b-0f3c30ebe988): IdentityPropagateID
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 459) - Closing reader
3 : (         messaging.propagateStartAndWait: 142) - Finished propagation with 3 replies
2 : (identity.(*Service).CreateIdentityInternal: 312) - New chain is
1d1ef434893ec192ac95ae117f46c17d8fc1af093cda0122117356d8f12b5a06
```

Traceback of `192.168.0.181` conode servers:

```
2 : (network.NewTLSListenerWithListenAddr.func1: 243) - Got new connection request from: 192.168.0.180:45844
3 : (            network.makeVerifier.func1.1: 276) - verify cert -> b097aca656644fc86eaade5f3e14d74a922e7d5e4d0e2f1a05d7a2750edfde02
3 : (            network.(*Router).handleConn: 273) - tls://[::]:6879 Handling new connection from tls://192.168.0.180:6879
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 455) - Starting node tls://192.168.0.181:6879 (98bcf88d-0de3-5f82-8bd1-c7a9df93d97f): SkipchainPropagate
3 : (         messaging.(*Propagate).Dispatch: 165) - tls://192.168.0.181:6879 Got data from tls://192.168.0.180:6879 and setting timeout to 15s
3 : (         messaging.(*Propagate).Dispatch: 174) - tls://192.168.0.181:6879 Sending to parent
3 : (         messaging.(*Propagate).Dispatch: 215) - tls://192.168.0.181:6879 done, isroot: false
3 : (           onet.(*TreeNodeInstance).Done: 571) - tls://192.168.0.181:6879 (98bcf88d-0de3-5f82-8bd1-c7a9df93d97f): SkipchainPropagate has finished. Deleting its resources
3 : (  onet.(*TreeNodeInstance).closeDispatch: 328) - Closing node tls://192.168.0.181:6879 (98bcf88d-0de3-5f82-8bd1-c7a9df93d97f): SkipchainPropagate
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 459) - Closing reader
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 455) - Starting node tls://192.168.0.181:6879 (afdc0311-180f-5e23-9547-1ec4a33b22e4): IdentityPropagateID
3 : (         messaging.(*Propagate).Dispatch: 165) - tls://192.168.0.181:6879 Got data from tls://192.168.0.180:6879 and setting timeout to 10s
3 : (identity.(*Service).propagateIdentityHandler: 704) - Storing identity in tls://192.168.0.181:6879
3 : (  identity.(*Service).setIdentityStorage: 725) - tls://192.168.0.181:6879 1d1ef434893ec192 map[omid:0xc420026290]
3 : (                identity.(*Service).save: 749) - Saving service
3 : (         messaging.(*Propagate).Dispatch: 174) - tls://192.168.0.181:6879 Sending to parent
3 : (         messaging.(*Propagate).Dispatch: 215) - tls://192.168.0.181:6879 done, isroot: false
3 : (           onet.(*TreeNodeInstance).Done: 571) - tls://192.168.0.181:6879 (afdc0311-180f-5e23-9547-1ec4a33b22e4): IdentityPropagateID has finished. Deleting its resources
3 : (  onet.(*TreeNodeInstance).closeDispatch: 328) - Closing node tls://192.168.0.181:6879 (afdc0311-180f-5e23-9547-1ec4a33b22e4): IdentityPropagateID
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 459) - Closing reader
E : (                         network.Marshal: 128) - Error for protobuf encoding: struct has no serializable fields (field nonces) (field Auth) &{Identities:map[�4�>�����F�}���	<�"sV��+Z:0xc42000c080 ��䫛�x@f���)��U�S���WX̽*�:0xc42011bb00] OldSkipchainKey:<nil> SkipchainKeyPair:<nil> Auth:0xc4200c6900}
E : (                         network.Marshal: 130) - goroutine 296 [running]:
runtime/debug.Stack(0xc42055d7f8, 0xc42055d810, 0x5d17a0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/dedis/onet/log.Stack(0x3, 0x23)
	/go/src/github.com/dedis/onet/log/testutil.go:80 +0x22
github.com/dedis/onet/network.Marshal(0x8b19c0, 0xc420196c30, 0xc420467960, 0x5d1272, 0x3, 0x3, 0xc4204679e0)
	/go/src/github.com/dedis/onet/network/encoding.go:130 +0x331
github.com/dedis/onet.(*Context).Save(0xc420095640, 0xc714c8, 0x7, 0x7, 0x8b19c0, 0xc420196c30, 0x3e0000c420467a10, 0x5d15ac)
	/go/src/github.com/dedis/onet/context.go:128 +0x42
github.com/dedis/cothority/identity.(*Service).save(0xc4200c68a0)
	/go/src/github.com/dedis/cothority/identity/service.go:750 +0xb2
github.com/dedis/cothority/identity.(*Service).setIdentityStorage(0xc4200c68a0, 0xc4200acb74, 0x20, 0x20, 0xc42000c080)
	/go/src/github.com/dedis/cothority/identity/service.go:727 +0x209
github.com/dedis/cothority/identity.(*Service).propagateIdentityHandler(0xc4200c68a0, 0x901220, 0xc4201d41b0)
	/go/src/github.com/dedis/cothority/identity/service.go:705 +0x2d1
github.com/dedis/cothority/identity.(*Service).(github.com/dedis/cothority/identity.propagateIdentityHandler)-fm(0x901220, 0xc4201d41b0)
	/go/src/github.com/dedis/cothority/identity/service.go:812 +0x3e
github.com/dedis/cothority/messaging.(*Propagate).Dispatch(0xc42009f2c0, 0x0, 0x0)
	/go/src/github.com/dedis/cothority/messaging/propagate.go:170 +0xd79
created by github.com/dedis/onet.(*Overlay).TransmitMsg
	/go/src/github.com/dedis/onet/overlay.go:170 +0x480

E : (                identity.(*Service).save: 752) - Couldn't save file: struct has no serializable fields (field nonces) (field Auth)
```

Trackback of `192.168.0.182` conode servers:

```
2 : (network.NewTLSListenerWithListenAddr.func1: 243) - Got new connection request from: 192.168.0.180:39868
3 : (            network.makeVerifier.func1.1: 276) - verify cert -> b097aca656644fc86eaade5f3e14d74a922e7d5e4d0e2f1a05d7a2750edfde02
3 : (            network.(*Router).handleConn: 273) - tls://[::]:6879 Handling new connection from tls://192.168.0.180:6879
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 455) - Starting node tls://192.168.0.182:6879 (344d9a67-926a-5adc-9268-5fb974fc658c): SkipchainPropagate
3 : (         messaging.(*Propagate).Dispatch: 165) - tls://192.168.0.182:6879 Got data from tls://192.168.0.180:6879 and setting timeout to 15s
3 : (         messaging.(*Propagate).Dispatch: 174) - tls://192.168.0.182:6879 Sending to parent
3 : (         messaging.(*Propagate).Dispatch: 215) - tls://192.168.0.182:6879 done, isroot: false
3 : (           onet.(*TreeNodeInstance).Done: 571) - tls://192.168.0.182:6879 (344d9a67-926a-5adc-9268-5fb974fc658c): SkipchainPropagate has finished. Deleting its resources
3 : (  onet.(*TreeNodeInstance).closeDispatch: 328) - Closing node tls://192.168.0.182:6879 (344d9a67-926a-5adc-9268-5fb974fc658c): SkipchainPropagate
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 459) - Closing reader
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 455) - Starting node tls://192.168.0.182:6879 (394b74ad-4875-589a-bdeb-3b7939e16c32): IdentityPropagateID
3 : (         messaging.(*Propagate).Dispatch: 165) - tls://192.168.0.182:6879 Got data from tls://192.168.0.180:6879 and setting timeout to 10s
3 : (identity.(*Service).propagateIdentityHandler: 704) - Storing identity in tls://192.168.0.182:6879
3 : (  identity.(*Service).setIdentityStorage: 725) - tls://192.168.0.182:6879 1d1ef434893ec192 map[omid:0xc42019d970]
3 : (                identity.(*Service).save: 749) - Saving service
E : (                         network.Marshal: 128) - Error for protobuf encoding: struct has no serializable fields (field nonces) (field Auth) &{Identities:map[��䫛�x@f���)��U�S���WX̽*�:0xc4200a3260 �4�>�����F�}���	<�"sV��+Z:0xc42049f4c0] OldSkipchainKey:<nil> SkipchainKeyPair:<nil> Auth:0xc42006a960}
E : (                         network.Marshal: 130) - goroutine 223 [running]:
runtime/debug.Stack(0xc42051b7f8, 0xc42051b810, 0x5d17a0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/dedis/onet/log.Stack(0x3, 0x23)
	/go/src/github.com/dedis/onet/log/testutil.go:80 +0x22
github.com/dedis/onet/network.Marshal(0x8b19c0, 0xc42017cc30, 0xc4204af960, 0x5d1272, 0x3, 0x3, 0xc4204af9e0)
	/go/src/github.com/dedis/onet/network/encoding.go:130 +0x331
github.com/dedis/onet.(*Context).Save(0xc42001f700, 0xc714c8, 0x7, 0x7, 0x8b19c0, 0xc42017cc30, 0x5e0000c4204afa10, 0x5d15ac)
	/go/src/github.com/dedis/onet/context.go:128 +0x42
github.com/dedis/cothority/identity.(*Service).save(0xc42006a900)
	/go/src/github.com/dedis/cothority/identity/service.go:750 +0xb2
github.com/dedis/cothority/identity.(*Service).setIdentityStorage(0xc42006a900, 0xc42011eb74, 0x20, 0x20, 0xc42049f4c0)
	/go/src/github.com/dedis/cothority/identity/service.go:727 +0x209
github.com/dedis/cothority/identity.(*Service).propagateIdentityHandler(0xc42006a900, 0x901220, 0xc4204e8120)
	/go/src/github.com/dedis/cothority/identity/service.go:705 +0x2d1
github.com/dedis/cothority/identity.(*Service).(github.com/dedis/cothority/identity.propagateIdentityHandler)-fm(0x901220, 0xc4204e8120)
	/go/src/github.com/dedis/cothority/identity/service.go:812 +0x3e
github.com/dedis/cothority/messaging.(*Propagate).Dispatch(0xc42008e320, 0x0, 0x0)
	/go/src/github.com/dedis/cothority/messaging/propagate.go:170 +0xd79
created by github.com/dedis/onet.(*Overlay).TransmitMsg
	/go/src/github.com/dedis/onet/overlay.go:170 +0x480

E : (                identity.(*Service).save: 752) - Couldn't save file: struct has no serializable fields (field nonces) (field Auth)
3 : (         messaging.(*Propagate).Dispatch: 174) - tls://192.168.0.182:6879 Sending to parent
3 : (         messaging.(*Propagate).Dispatch: 215) - tls://192.168.0.182:6879 done, isroot: false
3 : (           onet.(*TreeNodeInstance).Done: 571) - tls://192.168.0.182:6879 (394b74ad-4875-589a-bdeb-3b7939e16c32): IdentityPropagateID has finished. Deleting its resources
3 : (  onet.(*TreeNodeInstance).closeDispatch: 328) - Closing node tls://192.168.0.182:6879 (394b74ad-4875-589a-bdeb-3b7939e16c32): IdentityPropagateID
3 : (onet.(*TreeNodeInstance).dispatchMsgReader: 459) - Closing reader
```

**Comment by omidraha** [comment]
Also I have one question about storing key and value,
When I add a key on one conode server, how other conodes servers update and store this key?
How can I check that the key is successfully stored on others conodes servers?

**Comment by ineiti** [comment]
Hi there - thanks for checking out our repo. `cisc`, `identity`, `pop` are three services that will disappear in the upcoming version `v3`. As such they are not supported anymore, sorry.

`cisc` is based on the `skipchain` service, which serves as a basic blockchain structure, but without a global state or UTXOs. A much more powerful replacement for `cisc` is the `byzcoin` service, which implements a global state, transactions, view-changes, and much more. You can have a look here:

https://github.com/dedis/cothority/tree/master/byzcoin

If you have questions, don't hesitate to contact us, we can also invite you to our slack.

**Comment by robevansuk** [comment]
Hi, I was looking through this backlog of issues and was hoping I could get an invite to the slack channel you mention if possible.

**Comment by omidraha** [comment]
I and my colleague are maintaining [Helios Lib](https://github.com/anarvote/helios_lib). We founded a voting start up and planned to integrate our product with blockchain. We are interested to contribute in your project. How should I communicate our mail address to you to invite us to your slack?

**Comment by jeffallen** [comment]
Slack is for students in the DEDIS lab. Please use https://github.com/dedis/cothority#contact or github issues to communicate with us.

I am closing this issue for the moment, because I don't see another question, but if I missed it please re-open it.
