### ISSUE TITLE
panic in blscosi

### ISSUE THREAD

**Issue by jeffallen** [dedis/cothority#1725]
Using the instructions in README, I paniced the server:

```
blscosi sign -g dedis-cothority.toml /tmp/my_file
```

The panic was:

```
panic: interface conversion: kyber.Point is *bn256.pointG2, not *edwards25519.point

goroutine 24 [running]:
go.dedis.ch/kyber/v3/group/edwards25519.(*point).Equal(0xc0000c60b0, 0xbd7200, 0xc00000e1b0, 0xc0001c4248)
        /home/conode3/go/pkg/mod/go.dedis.ch/kyber/v3@v3.0.0-pre2/group/edwards25519/point.go:75 +0xdd
go.dedis.ch/kyber/v3/sign/cosi.NewMask(0xbd35e0, 0xc000212220, 0xc0001c6200, 0x1, 0x1, 0xbd7200, 0xc00000e1b0, 0xc0004f0480, 0x0, 0x0)
        /home/conode3/go/pkg/mod/go.dedis.ch/kyber/v3@v3.0.0-pre2/sign/cosi/cosi.go:248 +0x162
go.dedis.ch/cothority/v3/blscosi/protocol.(*BlsCosi).generateSignature(0xc0000a2f70, 0xc0001c8180, 0x2, 0xc0001c6190, 0x0, 0x0, 0x1)
        /home/conode3/cothority/blscosi/protocol/protocol.go:393 +0xd4
go.dedis.ch/cothority/v3/blscosi/protocol.(*BlsCosi).Dispatch(0xc0000a2f70, 0x0, 0x0)
        /home/conode3/cothority/blscosi/protocol/protocol.go:187 +0x58e
go.dedis.ch/onet/v3.(*Overlay).CreateProtocol.func1(0xbd1940, 0xc0000a2f70, 0xb1b02b, 0x13, 0xb156f0a697b7bccf, 0xfa5265d1dbcc86b5)
        /home/conode3/go/pkg/mod/go.dedis.ch/onet/v3@v3.0.0-pre3/overlay.go:555 +0x49
created by go.dedis.ch/onet/v3.(*Overlay).CreateProtocol
        /home/conode3/go/pkg/mod/go.dedis.ch/onet/v3@v3.0.0-pre3/overlay.go:554 +0x1fb
```

**Comment by jeffallen** [comment]
The toml file I used was:

```
[[servers]]
  Address = "tls://128.179.33.44:7000"
  Suite = "Ed25519"
  Public = "ec5c65a3c922d1df32075640e3de606197be24af76059a2ef145501122884bd3"
  Description = "EPFL Cothority-server"
  [servers.Services]
    [servers.Services.Skipchain]
      Public = "32ba0cccec06ac4259b39102dcba13677eb385e0fdce99c93406542c5cbed3ec6ac71a81b01207451346402542923449ecf71fc0d69b1d019df34407b532fb2a09005c801e359afb377cc3255e918a096912bf6f7b7e4040532404996e05f78c408760b57fcf9e04c50eb7bc413438aca9d653dd0b6a8353d128370ebd4bdb10"
      Suite = "bn256.adapter"
```

Note that it does not have an entry for servers.Services.blsCoSiService in it, because I edited it out. So apparently the client is falling back to ed25519, and the server is doing an unsafe cast.

**Comment by jeffallen** [comment]
I tagged onet v3.0.0-pre4 and upgraded cothority to use it (via "go get go.dedis.ch/onet@v3.0.0-pre4), and tested this interactively. The panic in the protocol no longer kills the server, though (as expected) the problem remains that the fallback to the ed25519 public key still causes us to fail to get the signature. The error is not clear at all, but it will have to be good enough for now:

```
# p is a copy of public.toml edited to remove the service key for the blscosi service
$ ./blscosi s -g p blscosi
 Couldn't create signature: no signature provided
```

**Comment by Gilthoniel** [comment]
The problem here is that the error happens in a child node and the failure makes the protocol to reach the timeout. Shall we create an issue to improve the error handling in the protocol ?
