### ISSUE TITLE
Fix java flaky test on Travis

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#1841]
```
Results :
Failed tests: 
  ByzCoinRPCTest.updateInterval:327
Tests run: 150, Failures: 1, Errors: 0, Skipped: 0
```

```
Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 70.522 sec <<< FAILURE! - in ch.epfl.dedis.byzcoin.ByzCoinRPCTest
updateInterval()  Time elapsed: 7.276 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
	at ch.epfl.dedis.byzcoin.ByzCoinRPCTest.updateInterval(ByzCoinRPCTest.java:327)
```

**Comment by Gilthoniel** [comment]
And the next one:
```
Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 94.026 sec <<< FAILURE! - in ch.epfl.dedis.byzcoin.ByzCoinRPCTest
updateRoster()  Time elapsed: 39.303 sec  <<< ERROR!
ch.epfl.dedis.lib.exception.CothorityCommunicationException: sending of ByzCoin/AddTxRequest failed with error: transaction didn't get included after 24s (2 * t_block * 12)
	at ch.epfl.dedis.byzcoin.ByzCoinRPCTest.updateRoster(ByzCoinRPCTest.java:459)
```
