### ISSUE TITLE
Invalid memory address

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/cothority#2062]
```
2 19/24/09 14:42:56.074204250: (skipchain.(*Service).StoreSkipBlockInternal: 380) - local://127.0.0.1:2000: sending request for height 1 to local://127.0.0.1:2000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b5628]

goroutine 33164 [running]:
go.etcd.io/bbolt.(*Bucket).Cursor(...)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:84
go.etcd.io/bbolt.(*Bucket).Get(0x0, 0xc0009bed99, 0x20, 0x20, 0x0, 0x8c0be0, 0xc002893fc8)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:260 +0x48
go.dedis.ch/cothority/v3/skipchain.(*SkipBlockDB).getFromTx(0xc003457100, 0xc0001b88c0, 0xc0009bed99, 0x20, 0x20, 0x8c08c2, 0xc002893e00, 0xc001f41b80)
	/cothority/skipchain/struct.go:1278 +0xc7
go.dedis.ch/cothority/v3/skipchain.(*SkipBlockDB).GetByID.func1(0xc0001b88c0, 0xe315d8, 0xc0001b88c0)
	/cothority/skipchain/struct.go:778 +0x74
go.etcd.io/bbolt.(*DB).View(0xc002893e00, 0xc001f41c38, 0x0, 0x0)
	/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:725 +0xb7
go.dedis.ch/cothority/v3/skipchain.(*SkipBlockDB).GetByID(0xc003457100, 0xc0009bed99, 0x20, 0x20, 0x20)
	/cothority/skipchain/struct.go:777 +0xce
go.dedis.ch/cothority/v3/skipchain.(*Service).bftForwardLink.func1(0xc0009bed36, 0xf4f, 0xf4f, 0xc00a989770, 0xc0009bed13, 0x20, 0x20, 0xc0004b4698, 0x4a4895)
	/cothority/skipchain/skipchain.go:1399 +0x3bc
go.dedis.ch/cothority/v3/skipchain.(*Service).bftForwardLink(0xc00a989770, 0xc0009bed13, 0x20, 0x20, 0xc0009bed36, 0xf4f, 0xf4f, 0x1)
	/cothority/skipchain/skipchain.go:1454 +0x9f
go.dedis.ch/cothority/v3/blscosi/protocol.(*SubBlsCosi).makeVerification(0xc00abf6840, 0xc004a1b3e0)
	/cothority/blscosi/protocol/sub_protocol.go:399 +0xd2
created by go.dedis.ch/cothority/v3/blscosi/protocol.(*SubBlsCosi).dispatchLeaf
	/cothority/blscosi/protocol/sub_protocol.go:339 +0x132
```

**Comment by ineiti** [comment]
Non-reproducible and old...
