### ISSUE TITLE
JVSS fails for some configurations

### ISSUE THREAD

**Issue by ineiti** [dedis/cothority#293]
While running JVSS on Deterlab, there were some difficult to reproduce exceptions:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x6704e6]

goroutine 16 [running]:
panic(0x8fac20, 0xc82000e0e0)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/dedis/crypto/poly.(*Schnorr).hashMessage(0xc82020e4e0, 0xc820418420, 0x20, 0x20, 0x7fb94335a810, 0xc8208a3680, 0x0, 0x0, 0x0, 0x0)
    /Users/altcode/Documents/go/src/github.com/dedis/crypto/poly/schnorr.go:121 +0x116
github.com/dedis/crypto/poly.(*Schnorr).NewRound(0xc82020e4e0, 0xc820418400, 0x7fb942c785f0, 0xc8208a3300, 0x0, 0x0)
    /Users/altcode/Documents/go/src/github.com/dedis/crypto/poly/schnorr.go:104 +0x1c1
github.com/dedis/cothority/protocols/jvss.(*LongtermRequest).newSigning(0xc82021e510, 0xc820418400, 0x7fb942c785f0, 0xc8208a3300, 0xc8206ca040)
    /Users/altcode/Documents/go/src/github.com/dedis/cothority/protocols/jvss/jvss.go:646 +0x5b
github.com/dedis/cothority/protocols/jvss.(*RequestBuffer).createSignatureResponse(0xc8201e8160, 0xc82011c20e, 0x20, 0x22, 0x1, 0x0)
    /Users/altcode/Documents/go/src/github.com/dedis/cothority/protocols/jvss/jvss.go:316 +0x1fc
github.com/dedis/cothority/protocols/jvss.(*RequestBuffer).addDeal(0xc8201e8160, 0x1e, 0xc82025ba20)
    /Users/altcode/Documents/go/src/github.com/dedis/cothority/protocols/jvss/jvss.go:492 +0x79e
github.com/dedis/cothority/protocols/jvss.(*RequestBuffer).addRandom(0xc8201e8160, 0x1, 0x1e, 0xc8201e50f4, 0xc40, 0xc40)
    /Users/altcode/Documents/go/src/github.com/dedis/cothority/protocols/jvss/jvss.go:517 +0x9f
github.com/dedis/cothority/protocols/jvss.(*JVSSProtocol).waitForRandom(0xc820202380)
    /Users/altcode/Documents/go/src/github.com/dedis/cothority/protocols/jvss/jvss.go:261 +0xb94
created by github.com/dedis/cothority/protocols/jvss.NewJVSSProtocol
    /Users/altcode/Documents/go/src/github.com/dedis/cothority/protocols/jvss/jvss.go:139 +0xfcd
```

This was on March 16th, 2016 - try

https://github.com/dedis/cothority/pull/257/commits/417e6e850f537a21ae33de780270b7e4bab99654

with 

`Doing run simulation:JVSS servers:32 hosts:32 bf:2 rounds:5`

**Comment by Daeinar** [comment]
TODO: Check if it still fails with the new JVSS implementaiton.

**Comment by Liamsi** [comment]
@Daeinar @ineiti does this still fail with #333? Or in other words: when you ran the simulations today did you also try:

" 417e6e8
with
`Doing run simulation:JVSS servers:32 hosts:32 bf:2 rounds:5`
"

**Comment by Daeinar** [comment]
I haven't tried it yet on Deterlab. Last time we checked they did not have 32 servers available.

**Comment by Liamsi** [comment]
OK, I'll test it next week then (if no-one else did in the mean-time)

**Comment by Daeinar** [comment]
Cool thx!

**Comment by Liamsi** [comment]
>this was my first intention - yes. It does look good. I just saw some cosmetic issues I’m cleaning up. But JVSS seems to pass. So #293 seems to be good to be closed. 

@ineiti Is it safe to close this issue?

**Comment by ineiti** [comment]
I guess so ;)
